version: "3.9"

services:
  database:
    image: mysql/mysql-server:8.0
    container_name: pracownicy-database
    environment:
      - MYSQL_USER=administrator
      - MYSQL_PASSWORD=pracownicy-password
      - MYSQL_DATABASE=pracownicy

  phpmyadmin:
    image: phpmyadmin
    container_name: pracownicy-phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=database
    depends_on:
      database:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: pracownicy-api
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./api:/app/api
      - ./validation:/app/validation
      - /app/api/node_modules
      - /app/validation/node_modules

  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: pracownicy-app
    ports:
      - "5173:5173"
    environment:
      - VITE_APP_API_URL=http://localhost:3000/
    depends_on:
      api:
        condition: service_started
    volumes:
      - ./app:/app/app
      - ./validation:/app/validation
      - /app/app/node_modules
      - /app/validation/node_modules
